server:
  port: 9081

info:
  artifact: stock-prices-producer
  version: 1.0

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

jms:
  stock-prices:
    queue:
      name: stock.prices.queue
    topic:
      name: stock.prices.topic
