spring:
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: localhost