server:
  port: 9081

application:
  name: stock-prices-producer
  version: 1.0

spring:
  application:
    name: stock-prices-producer
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

jms:
  stock-prices:
    queue:
      name: stock.prices.queue
    topic:
      name: stock.prices.topic
