version: '3.7'

networks:
  stock-market-network:
    driver: bridge

services:
  activemq:
    image: webcenter/activemq:latest
    ports:
    - "1883:1883"   # mqtt
    - "5672:5672"   # amqp
    - "8161:8161"   # ui
    - "61613:61613" # stomp
    - "61614:61614" # websocket
    - "61616:61616" # jms
    environment:
      ACTIVEMQ_NAME: amq
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: 'True'
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
      ACTIVEMQ_STATIC_QUEUES: stock.prices.queue
      ACTIVEMQ_STATIC_TOPICS: stock.prices.topic
    networks: [stock-market-network]
    volumes:
    - /container_data/activemq/data:/data/activemq
    - /container_data/activemq/log:/var/log/activemq

  stock-prices-producer:
    container_name: stock-prices-producer
    build:
      context: ./stock-prices-producer
    image: stock-prices-producer
    expose:
    - 9081
    environment:
    - "SPRING_PROFILES_ACTIVE=container"
    links:
    - activemq
    networks: [stock-market-network]
    logging:
      driver: json-file

  stock-prices-consumer:
    container_name: stock-prices-consumer
    build:
      context: ./stock-prices-consumer
    image: stock-prices-consumer
    expose:
    - 9082
    environment:
    - "SPRING_PROFILES_ACTIVE=container"
    links:
    - activemq
    networks: [stock-market-network]
    logging:
      driver: json-file
