version: '3.7'

networks:
  stock-market-network:
    driver: bridge

services:
  activemq:
    image: webcenter/activemq:latest
    container_name: activemq
    ports:
    - "1099:1099"   # jmx
    - "1883:1883"   # mqtt
    - "5672:5672"   # amqp
    - "8161:8161"   # ui
    - "61613:61613" # stomp
    - "61614:61614" # websocket
    - "61616:61616" # jms
    environment:
      ACTIVEMQ_NAME: amq
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: 'True'
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
      ACTIVEMQ_STATIC_QUEUES: stock.prices.queue
      ACTIVEMQ_STATIC_TOPICS: stock.prices.topic
    networks: [stock-market-network]
    volumes:
    - /home/steph/container_data/activemq/data:/data/activemq
    - /home/steph/container_data/activemq/log:/var/log/activemq

  logstash:
    image: logstash:${TAG_ELK}
    container_name: logstash
    command: logstash -f /config/logstash.conf
    environment:
    - LS_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
    - ./logstash/config:/config
    ports:
    - "5000:5000"
    - "9600:9600"
    links:
    - elasticsearch
    networks: [stock-market-network]

  elasticsearch:
    image: elasticsearch:${TAG_ELK}
    container_name: elastic
    environment:
    - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
    - 9200:9200
    - 9300:9300
    networks:
    - stock-market-network

  kibana:
    image: kibana:${TAG_ELK}
    container_name: kibana
    ports:
    - 5601:5601
    networks:
    - stock-market-network
    depends_on:
    - elasticsearch

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
    - stock-market-network

  grafana:
    build: './grafana'
    container_name: 'grafana'
    ports:
    - '3000:3000'
    links:
    - prometheus
    networks:
    - stock-market-network

  config-service:
    container_name: config-service
    build: ./config-service
    image: config-service:latest
    ports:
    - "8888:8888"
    environment:
    - "SPRING_PROFILES_ACTIVE=native"
    networks: [stock-market-network]
    logging:
      driver: json-file

  stock-prices-producer:
    container_name: stock-prices-producer
    build: ./stock-prices-producer
    image: stock-prices-producer:latest
    ports:
    - "9081:9081"
    environment:
    - "SPRING_PROFILES_ACTIVE=container"
    links:
    - activemq
    - logstash
    networks: [stock-market-network]
    volumes:
      - /home/steph/container_data/stock-prices-producer:/tmp
    logging:
      driver: json-file

  mongo:
    image: mongo:3.4.18
    container_name: mongodb
    ports:
    - "27017:27017"
    environment:
    - MONGO_INITDB_DATABASE=admin
    - MONGO_INITDB_ROOT_USERNAME=admuser
    - MONGO_INITDB_ROOT_PASSWORD=admpass
    command: mongod --smallfiles
    networks: [stock-market-network]
    volumes:
    - ./mongodb/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    - /home/steph/container_data/mongodb/db:/data/db
    - /home/steph/container_data/mongodb/configdb:/data/configdb

  stock-prices-consumer:
    container_name: stock-prices-consumer
    build: ./stock-prices-consumer
    image: stock-prices-consumer
    ports:
    - "9082:9082"
    environment:
    - "SPRING_PROFILES_ACTIVE=container"
    links:
    - activemq
    networks: [stock-market-network]
    volumes:
    - /home/steph/container_data/stock-prices-consumer:/tmp
    logging:
      driver: json-file
