server:
  port: 9082

application:
  name: stock-prices-consumer
  version: 1.0

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  data:
    mongodb:
      host: localhost
      port: 27017
      database: stock_prices
      username: stock_prices_user
      password: stock_prices_password

jms:
  stock-prices:
    queue:
      name: stock.prices.queue
    topic:
      name: stock.prices.topic
